### ISSUE TITLE
[PE-D][Tester A] Duplicate format: 'undo' in undo command

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S2-CS2103T-T11-4/tp#168]
![image.png](https://raw.githubusercontent.com/Jarrett0203/ped/main/files/d340bec8-40e5-497c-b9b8-7ea70018e14d.png)

-------------
Labels: `severity.VeryLow` `type.DocumentationBug`
original: Jarrett0203/ped#4

**Comment by CedricPei** [comment]
Found and solved.
